### ISSUE TITLE
Replace `ipld-dag-pb` with `@ipld/dag-pb`

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipld-explorer-components#329]
https://github.com/ipfs/ipld-explorer-components/blob/9c01a2a37859752b90307318cfcbe032d68746b4/package.json#L176

Required for https://github.com/ipfs/ipfs-webui/pull/1840

**Comment by SgtPooki** [comment]
Following instructions at https://www.npmjs.com/package/@ipld/dag-pb#user-content-createnode--createlink

**Comment by SgtPooki** [comment]
some dependencies aren't being loaded properly..?

```bash
    ReferenceError: TextDecoder is not defined

       5 | import * as Block from 'multiformats/block'
       6 | import { sha256 as hasher } from 'multiformats/hashes/sha2'
    >  7 | import * as codec from '@ipld/dag-pb'
         | ^
       8 |
       9 | import resolveIpldPath, { findLinkPath } from './resolve-ipld-path'
      10 |

      at Object.<anonymous> (node_modules/@ipld/dag-pb/cjs/src/pb-decode.js:5:21)
      at Object.<anonymous> (node_modules/@ipld/dag-pb/cjs/src/index.js:6:16)
      at Object.<anonymous> (src/lib/resolve-ipld-path.test.js:7:1)
```
